### ISSUE TITLE
Error caused by incompatible kue versions

### ISSUE THREAD

**Issue by rtens** [layerhq/node-layer-webhooks-services#14]
## Description

It seems that if you have `layer-webhooks-services` as a dependency of a project which also has a dependency on `kue`, but in a version that is incompatible with the version required by `layer-webhooks-services` and connect to redis on a non-default URL (i.e. not `127.0.0.1:6379`), the connection with redis fails with the following message.

```
events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: Redis connection to 127.0.0.1:6379 failed - connect ECONNREFUSED 127.0.0.1:6379
    at Object.exports._errnoException (util.js:1022:11)
    at exports._exceptionWithHostPort (util.js:1045:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1087:14)
```

## Cause

The error originates from [listen.js](https://github.com/layerhq/node-layer-webhooks-services/blob/master/src/listen.js#L52) where `var queue = kue.createQueue();` is called. This assumes that a `Queue` has been created before as described in the [readme](https://github.com/layerhq/node-layer-webhooks-services#setup) but if the `layer-webhooks-services` has its own version of `key` installed, then this doesn't work.

## Minimal setup

`server.js`
```
var kue = require('kue');
kue.createQueue({
    prefix: 'kue',
    jobEvents: false,
    redis: 'A_NON_DEFAULT_REDIS_URL'
});
require('./node_modules/layer-webhooks-services/src/listen');
```

`package.json`
```
{
  "name": "kue-test",
  "version": "1.0.0",
  "description": "",
  "main": "server.js",
  "dependencies": {
    "kue": "^0.11.5",
    "layer-webhooks-services": "^1.0.7"
  }
}
```

Error reproduction
```
npm install
node server.js
```

## Work-around

Requiring a compatible version of `kue` solves the problem.

```
sed -i -- 's/0\.11\.5/0\.10\.5/g' package.json
rm -rf node_modules
npm install
node server.js
```

**Comment by michaelkantor** [comment]
I'm not sure if I've followed this correctly...

1. All of layer's node modules that I've checked use the same version of kue in their package.json files
2. From this I'd have to assume that what you are reporting is: if your app uses a different version of kue from layer's modules, then your apps fail.  Is that correct?
3. Are you asking that all kue dependencies be updated to the latest to prevent this from happening?
4. Are you asking for better detection to detect when there are multiple versions of kue present?
5. Have I totally misunderstood the problem? You mention an issue around the `key` which hasn't fit into the understanding I describe above.

Michael
