### ISSUE TITLE
Cannot read property 'name' of undefined

### ISSUE THREAD

**Issue by lisbakke** [layerhq/node-layer-webhooks-services#8]
I'm trying to setup a webhook to be called on `message.sent`. I'm getting this error on my nodejs server when a message is sent:
```
TypeError: Cannot read property 'name' of undefined
    at /app/node_modules/layer-webhooks-services/src/listen.js:95:26
    at Layer.handle [as handle_request] (/app/node_modules/express/lib/router/layer.js:95:5)
    at next (/app/node_modules/express/lib/router/route.js:131:13)
    at handleValidation (/app/node_modules/layer-webhooks-services/src/listen.js:134:31)
    at Layer.handle [as handle_request] (/app/node_modules/express/lib/router/layer.js:95:5)
    at next (/app/node_modules/express/lib/router/route.js:131:13)
    at /app/node_modules/body-parser/lib/read.js:129:5
    at invokeCallback (/app/node_modules/raw-body/index.js:262:16)
    at done (/app/node_modules/raw-body/index.js:251:7)
    at IncomingMessage.onEnd (/app/node_modules/raw-body/index.js:308:7)
    at emitNone (events.js:80:13)
    at IncomingMessage.emit (events.js:179:7)
    at endReadableNT (_stream_readable.js:913:12)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
```

I registered a webhook on the dashboard to `/message` with `message.sent` and has been successfully activated.

Here is my code in my server for listening for this webhook:

```
// Provide a webhook definition
  var webhook = {
    name: 'message',
    path: '/message',
    events: ['message.sent']
  };

// Listen for a webhook
  webhooksServices.listen({
    expressApp: app,
    secret: SECRET,
    hooks: [webhook]
  });

  queue.process(webhook.name, function(job, done) {
    var webhookEvent = job.data;
    var message = webhookEvent.message;
    console.log('Message Received from: ' + message.sender.user_id);
  });
```

I see that the webhooks are being called, but Layer's `listen.js` is hitting an error because `req.body.config` on line 95 is undefined.

Do you guys know what could be going on?

**Comment by lisbakke** [comment]
(specifically, `config` object on `req.body` is undefined. `req.body` is OK)

**Comment by lisbakke** [comment]
Here is a sanitizied version of `req.body`
```
{
  "event": {
    "id": "<EVENT_ID>",
    "type": "message.sent",
    "created_at": "2016-04-15T17:26:53.007Z",
    "actor": {
      "user_id": "<USER_ID>"
    }
  },
  "message": {
    "id": "layer:///messages/<MESSAGE_ID>",
    "conversation": {
      "id": "layer:///conversations/<CONVERSATION_ID>",
      "url": "https://api.layer.com/apps/<APP_ID>/conversations/<CONVERSATION_ID>"
    },
    "parts": [{
      "id": "layer:///messages/<MESSAGE_ID>/parts/0",
      "mime_type": "text/plain",
      "body": "Received message: F"
    }],
    "sent_at": "2016-04-15T17:26:53.007Z",
    "sender": {
      "user_id": "<USER_ID>"
    },
    "recipient_status": {
      "<USER_ID>": "read",
      "<USER_ID>": "sent"
    }
  }
}
```

**Comment by michaelkantor** [comment]
The fact that your req.body does not contain a config, makes me assume that the webhook was created via the Developer Dashboard rather than using the `register()` call.

Next steps:
1. You should log into the developer dashboard and delete all of your webhooks and recreate them with the `register()` call
2. I need to make `listen()` more tolerant of Webhooks created by hand.

**Comment by lisbakke** [comment]
Thanks for the quick response @michaelkantor.

I actually originally started out configuring via `register()` call but had a nearly identical issue in a different script, `register.js`. In `getWebhook` filter, I get:

```
TypeError: Cannot read property 'name' of undefined
    at /path/to/node_modules/layer-webhooks-services/src/register.js:80:28
    at Array.filter (native)
    at getWebhook (/path/to/node_modules/layer-webhooks-services/src/register.js:79:25)
    at registerHook (/path/to/node_modules/layer-webhooks-services/src/register.js:86:19)
    at Array.forEach (native)
    at /path/to/node_modules/layer-webhooks-services/src/register.js:47:11
    at IncomingMessage.<anonymous> (/path/to/node_modules/layer-webhooks/lib/request.js:115:10)
    at emitNone (events.js:72:20)
    at IncomingMessage.emit (events.js:166:7)
    at endReadableNT (_stream_readable.js:905:12)
    at doNTCallback2 (node.js:441:9)
    at process._tickCallback (node.js:355:17)
```

This is the first `webhook` object that ends up throwing the error -- you can see it has no `config` field:

```
‌{
  "id": "layer:///apps/<APP_ID>/webhooks/<WEBHOOK_ID>",
  "url": "https://api.layer.com/apps/<APP_ID>/webhooks/<WEBHOOK_ID>",
  "version": "1.0",
  "target_url": "https://sidekick-test.herokuapp.com/message",
  "events": ["message.sent"],
  "status": "active",
  "created_at": "2016-04-15T16:52:27.694Z"
}
```

**Comment by lisbakke** [comment]
OK, I may have found the issue. It looks like by deleting all webhooks created in the dashboard I can get around this issue. It seems like all dashboard webhooks do not have a `config` object. Since `register.js` and `listen.js` look at all webhook definitions, they will crash as long as there is a dashboard webhook on my account.
